ALTER TABLE voice_settings ADD COLUMN IF NOT EXISTS chat_notify_sound BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE voice_settings ADD COLUMN IF NOT EXISTS chat_mention_sound BOOLEAN NOT NULL DEFAULT TRUE;
